# Generated by Django 4.0.6 on 2022-11-05 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyArtist',
            fields=[
                ('artist_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'spotify_artist',
            },
        ),
        migrations.CreateModel(
            name='SpotifyPlaylist',
            fields=[
                ('playlist_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spotify_playlist',
            },
        ),
        migrations.CreateModel(
            name='SpotifyTracks',
            fields=[
                ('track_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('track_name', models.CharField(max_length=255)),
                ('danceability', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('valence', models.IntegerField()),
                ('acousticness', models.IntegerField()),
                ('loudness', models.IntegerField()),
                ('tempo', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicApp.spotifyartist')),
                ('playlist', models.ManyToManyField(to='MusicApp.spotifyplaylist')),
            ],
            options={
                'db_table': 'spotify_tracks',
            },
        ),
    ]
